.MODEL SMALL
.STACK 64H
.DATA
	ARR DB 0,1,2,3,4,5,6,7,8,9
	KEY DB ?
	POS DB ?
	FLAG DB ?
	MSG1 DW "KEY IN FOUND AT "
	RES DB "  POSITION",13,10," $"
	MSG2 DW 'KEY NOT FOUND!!!.$'
.CODE
	START:
		MOV AX, @DATA
		MOV DS, AX
		LEA SI, ARR
		MOV CX, 000AH
		MOV KEY, 000CH
		MOV POS, 0000H
		MOV FLAG, 0000H
		AGAIN:
			INC POS
			MOV AL, [SI]
			CMP AL, KEY
			JE SUCCESS
			INC SI
			LOOP AGAIN
		CMP FLAG, 0000H
		JZ FAIL
		SUCCESS:
			MOV AL, POS
			ADD AL, '0'
			MOV RES, AL
			LEA DX, MSG1
			JMP DISP
		FAIL:
			LEA DX, MSG2
		DISP:
			MOV AH, 09H
			INT 21H
			MOV AH, 4CH
			INT 21H
		END START
			